#pragma once

//TODO convert to hex and clean up
typedef enum BSP_RVAL {
    BSP_RVAL_BOARD_CONFIG_INVALID=262144,
    BSP_RVAL_CFG_CORRUPTED=8,
    BSP_RVAL_DEVICE_BUSY=32,
    BSP_RVAL_DEVICE_ERROR=16,
    BSP_RVAL_DEVICE_NOT_FOUND=32768,
    BSP_RVAL_ENTITY_LIST_FULL=512,
    BSP_RVAL_HEAP_ERROR=256,
    BSP_RVAL_INVALID_INSTANCE=4,
    BSP_RVAL_INVALID_PARAMETER=16384,
    BSP_RVAL_OK=0,
    BSP_RVAL_OS_ERROR=64,
    BSP_RVAL_QUERY_UNAVAILABLE=4096,
    BSP_RVAL_REQUEST_DENIED=65536,
    BSP_RVAL_SPECIFIED_SIZE_INVALID=128,
    BSP_RVAL_UNKNOWN_ATTRIBUTE=2,
    BSP_RVAL_UNKNOWN_DEVICE=8192,
    BSP_RVAL_UNKNOWN_ENTITY=1,
    BSP_RVAL_UNKNOWN_HARDWARE_VERSION=2048,
    BSP_RVAL_UNSUPPORTED_METHOD=1024,
    BSP_RVAL_UNSUPPORTED_PARAMETER=131072
} BSP_RVAL;

typedef enum BSP_ATTRIBUTE_OPTIONS {
    BSP_AO_INIT_GLOBAL=4,
    BSP_AO_QUERY_DATA_DIRECT=1,
    BSP_AO_QUERY_DATA_INDIRECT=2,
    BSP_AO_SHUTDOWN_GLOBAL=8
} BSP_ATTRIBUTE_OPTIONS;

typedef enum BSP_ATTRIBUTE_PERMISSIONS {
    BSP_PERMISSIONS_ALL=65535,
    BSP_PERMISSIONS_INTERNAL_EXCLUSIVE=-8,
    BSP_PERMISSIONS_INTERNAL=0x80000000,
    BSP_PERMISSIONS_IOS=255,
    BSP_PERMISSIONS_IOS_SUPV=240,
    BSP_PERMISSIONS_IOS_SUPV_INIT=64,
    BSP_PERMISSIONS_IOS_SUPV_READ=16,
    BSP_PERMISSIONS_IOS_SUPV_SHUTDOWN=128,
    BSP_PERMISSIONS_IOS_SUPV_WRITE=32,
    BSP_PERMISSIONS_IOS_USER=15,
    BSP_PERMISSIONS_IOS_USER_INIT=4,
    BSP_PERMISSIONS_IOS_USER_READ=1,
    BSP_PERMISSIONS_IOS_USER_SHUTDOWN=8,
    BSP_PERMISSIONS_IOS_USER_WRITE=2,
    BSP_PERMISSIONS_PPC=65280,
    BSP_PERMISSIONS_PPC_SUPV=61440,
    BSP_PERMISSIONS_PPC_SUPV_INIT=16384,
    BSP_PERMISSIONS_PPC_SUPV_READ=4096,
    BSP_PERMISSIONS_PPC_SUPV_SHUTDOWN=32768,
    BSP_PERMISSIONS_PPC_SUPV_WRITE=8192,
    BSP_PERMISSIONS_PPC_USER=3840,
    BSP_PERMISSIONS_PPC_USER_INIT=1024,
    BSP_PERMISSIONS_PPC_USER_READ=256,
    BSP_PERMISSIONS_PPC_USER_SHUTDOWN=2048,
    BSP_PERMISSIONS_PPC_USER_WRITE=512
} BSP_ATTRIBUTE_PERMISSIONS;
typedef enum BSP_ATTRIBUTE_PERMISSIONS BSP_CLIENT_CREDENTIALS;

typedef enum BSP_ENTITY_OPTIONS {
    BSP_EO_FLAT_INSTANCES=2,
    BSP_EO_NONE=0,
    BSP_EO_NO_INFO_API_LOGGING=1
} BSP_ENTITY_OPTIONS;
